config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pins do
    member do
      put "like", to: "pins#upvote"
    end
  end

  root "pins#index" 
end

app/models/pin.rb
class Pin < ActiveRecord::Base
	acts_as_votable
	belongs_to :user
	mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController

	before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
	before_action :authenticate_user!, except: [:index, :show]
	
	def index
		@pins = Pin.all.order("created_at DESC")
	end

	def show
	end

	def new
		@pin = current_user.pins.build
	end

	def create
		@pin = current_user.pins.build(pin_params)

		if @pin.save
			redirect_to @pin, notice: "Pin was successfully created"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @pin.update(pin_params)
			redirect_to @pin, notice: "Pin was successfully updated"
		else
			render 'edit'
		end
	end

	def destroy
		@pin.destroy
		redirect_to root_path
	end

	def upvote
		@pin.upvote_by current_user
		redirect_to :back
	end

	private

	def pin_params
		params.require(:pin).permit(:description, :picture, :picture_cache)
	end

	def find_pin
		@pin = Pin.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>photo_box</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-brand">
        <%= link_to "Photo Box", root_path %>
      </div>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to "등록", new_pin_path %>
          </li>
          <li>
            <%= link_to "계정", edit_user_registration_path %>
          </li>
          <li>
            <%= link_to "로그아웃", destroy_user_session_path, method: :delete %>
          </li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to "회원가입", new_user_registration_path %>
          </li>
          <li>
            <%= link_to "로그인", new_user_session_path %>
          </li>
        </ul>
      <% end %>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-info" %>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/pins/_form.html.erb
<%= simple_form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="errors">
      <h2>
        <%= pluralize(@pin.errors.count, "error") %>등록에 실패하였습니다.
      </h2>
      <ul>
        <% @pin.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.input :picture, as: :file, input_html: { class: 'form-control' } %>
    <%= f.hidden_field :picture_cache %>
  </div>
  <div class="form-group">
    <%= f.input :description, input_html: { class: 'form-control' } %>
  </div>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>


	

app/views/pins/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>변경화면</h1>
      </div>
      <div class="panel-body">
        <strong class="center">등록된 이미지</strong>
        <br/>
        <%= image_tag @pin.picture.url{:medium} %>
        <br/>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/pins/index.html.erb
<div class="transitions-enabled" id="pins">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to (image_tag pin.picture.url), pin %>
    </div>
  <% end %>
</div>

app/views/pins/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>새로운 사진등록</h1>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/pins/show.html.erb
<div class="row" id="pin_show">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading pin_image">
        <%= image_tag @pin.picture.url %>
      </div>
      <div class="panel-body">
        <h1>
          <%= @pin.description %>
        </h1>
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="col-md-6">
            <p class="user">
              photo upload by
              <%= @pin.user.email %>
            </p>
          </div>
          <div class="col-md-6">
            <div class="btn-group pull-right">
              <%= link_to like_pin_path(@pin), method: :put, class: "btn btn-default" do %>
                <span class="glyphicon glyphicon-heart">
                  <%= @pin.get_upvotes.size %>
                </span>
              <% end %>
              <% if user_signed_in? %>
                <%= link_to "수정", edit_pin_path, class: "btn btn-default" %>
                <%= link_to "삭제", pin_path, method: :delete, data: { confirm: "정말 삭제하시겠습니까?" }, class: "btn btn-default" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>